#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

node ./node_modules/home-book-scripts/scripts/branchNameLint.js
npx stylelint "**/*.scss"
npm run eslint-ts
npm run eslint-tsx
npm run prettier:check
